services:
    postgresql:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: "teste"
            POSTGRES_USER: "teste"
            POSTGRES_DB: "teste"
        volumes:
            - ./pgdata:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        ports:
            - 7500:80
        depends_on:
            - postgresql